In [63]:
import pandas as pd
import numpy as np

In [64]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [65]:
df= pd.read_csv(r'C:\Users\ctani\OneDrive\Desktop\macine learning\data set\covid_toy.csv')

In [66]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [67]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2,random_state=0)

In [69]:
x_train

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

# Aam zindagi

In [70]:
si=SimpleImputer()

In [71]:

x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [72]:
x_test_fever.shape

(20, 1)

In [73]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
X_test_cough = oe.transform(x_test[['cough']])

X_train_cough.shape

(80, 1)

In [74]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(x_train[['gender','city']]).toarray()

# also the test data
X_test_gender_city = ohe.fit_transform(x_test[['gender','city']]).toarray()

X_train_gender_city.shape

(80, 4)

In [75]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [76]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,X_train_gender_city,X_train_cough),axis =1)
x_test_transformed=np.concatenate((x_test_age,x_test_fever,X_test_gender_city,X_test_cough),axis=1)


x_train_transformed.shape

(80, 7)

# Mentos Zindagi

In [77]:
from sklearn.compose import ColumnTransformer

In [80]:
transformer= ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])],
                                            remainder='passthrough')

In [81]:
transformer.fit_transform(x_train).shape

(80, 7)

In [82]:
transformer.transform(x_test).shape

(20, 7)